import type {ModuleName} from "./supabase/types";
export type Field={key:string;label:string;type?:"text"|"email"|"number"|"date"|"time"|"select"|"textarea";options?:string[]};
export type ModuleConfig={table:ModuleName;title:string;eyebrow:string;description:string;singular:string;fields:Field[];columns:string[]};
export const modules:Record<string,ModuleConfig>={
 clients:{table:"clients",title:"Clients",eyebrow:"RELATIONSHIPS",description:"One source of truth for every relationship, conversation, and opportunity.",singular:"client",columns:["name","company","email","status"],fields:[{key:"name",label:"Client name"},{key:"company",label:"Company"},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone"},{key:"status",label:"Status",type:"select",options:["lead","active","inactive"]},{key:"notes",label:"Notes",type:"textarea"}]},
 projects:{table:"projects",title:"Projects",eyebrow:"DELIVERY SYSTEM",description:"Connect client outcomes, budgets, deadlines, and production status.",singular:"project",columns:["name","client_name","status","deadline"],fields:[{key:"name",label:"Project name"},{key:"client_name",label:"Client"},{key:"status",label:"Status",type:"select",options:["planning","active","review","complete","archived"]},{key:"priority",label:"Priority",type:"select",options:["low","medium","high","urgent"]},{key:"deadline",label:"Deadline",type:"date"},{key:"budget",label:"Budget",type:"number"},{key:"description",label:"Description",type:"textarea"}]},
 studio:{table:"studio_bookings",title:"Studio",eyebrow:"STUDIO OPERATIONS",description:"Coordinate spaces, bookings, crews, equipment, and shoot readiness.",singular:"booking",columns:["title","space","booking_date","status"],fields:[{key:"title",label:"Booking title"},{key:"client_name",label:"Client"},{key:"space",label:"Space",type:"select",options:["Indoor Studio","Podcast Floor"]},{key:"booking_date",label:"Date",type:"date"},{key:"start_time",label:"Start time",type:"time"},{key:"end_time",label:"End time",type:"time"},{key:"status",label:"Status",type:"select",options:["enquiry","confirmed","in_progress","completed","cancelled"]},{key:"notes",label:"Production notes",type:"textarea"}]},
 staff:{table:"staff",title:"Staff",eyebrow:"TEAM DIRECTORY",description:"Manage the people responsible for studio, production, operations, and creative delivery.",singular:"staff member",columns:["name","role","status","created_at"],fields:[{key:"name",label:"Name"},{key:"role",label:"Role"},{key:"status",label:"Status",type:"select",options:["active","inactive"]}]},
 finance:{table:"transactions",title:"Finance",eyebrow:"BUSINESS CONTROL",description:"Track money earned, money owed, expenses, and operating performance.",singular:"transaction",columns:["description","kind","amount","status"],fields:[{key:"description",label:"Description"},{key:"kind",label:"Type",type:"select",options:["income","expense"]},{key:"amount",label:"Amount",type:"number"},{key:"status",label:"Status",type:"select",options:["pending","paid","overdue","cancelled"]},{key:"due_date",label:"Due date",type:"date"},{key:"category",label:"Category"},{key:"notes",label:"Notes",type:"textarea"}]}
};
